default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  port: 3306
  timeout: 5000
  adapter: 'mysql2'
  host: <%= ENV['MYSQL_HOST'] %>
  # any other standard AR configurations

development:
  <<: *default
  database: glexport_development

test:
  <<: *default
  database: glexport_test

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
